[package]
name = "aciddm3_daleth"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]
members = ["xtask"]

[dependencies]
aciddm3_atom_func = { git = "https://github.com/aciddm3/atom_func.git", features = [
    "sexpr_parser", "simplifier"
] }
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug", features = [
    "vst3",
] }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug" }
nih_plug_derive = { git = "https://github.com/robbert-vdh/nih-plug" }
parking_lot = "0.12.5"
rfd = "0.17.2"
serde_json = "1.0.149"
serde = "1.0.228"
