[package]
name = "simple_midi_sampler_vst3"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]
members = [
    "xtask"
]

[dependencies]
hound = "3.5.1"
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug", features = ["vst3"] }
nih_plug_derive = { git = "https://github.com/robbert-vdh/nih-plug" }